server:
  port: 8080
  servlet:
    context-path: /calmistry

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://metro.proxy.rlwy.net:24473/calmistry}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:vNuRxEsasQqlbOZUsraXWnRGoQIqXkVN}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#outbound:
#  identity:
#    client-id: "<clientId>"
#    client-secret: "<clientSecret>"
#    redirect-uri: "http://localhost:3000/authenticate"

  application:
    name: spring-ai-demo
  ai:
    openai:
      api-key: ${SPRING_AI_KEY:your_custom_proxy_key_here}
      base-url: ${SPRING_AI_BASE_URL:https://ccs.qatthcv.com/}
      chat:
        options:
          model: gpt-5.2

# JWT Configuration
jwt:
  signerKey: ${JWT_SIGNER_KEY:wYUihtKXpSs_rDJXC2wdSpL0O03rp7UK7KGk4_GoQkSPaRJ8z3__8hvl_NBOIams3cweOfBvBoyFXceds_VxA}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

# OpenAI Configuration
openai:
  api-key: ${OPENAI_API_KEY:your_openai_key_here}
  model: gpt-5.2

# Gemini AI Configuration
gemini:
  api-key: ${GEMINI_API_KEY:your_gemini_key_here}
  model: gemini-1.5-flash

# Cloudinary Configuration
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dculsqafi}
  api-key: ${CLOUDINARY_API_KEY:885716972975153}
  api-secret: YjMVc_vvJAewdntYU4j0kFOaEV4 


