server:
  port: 8080
  servlet:
    context-path: /calmistry

spring:
  datasource:
    url: "jdbc:mysql://metro.proxy.rlwy.net:24473/calmistry"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: vNuRxEsasQqlbOZUsraXWnRGoQIqXkVN
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#outbound:
#  identity:
#    client-id: "<clientId>"
#    client-secret: "<clientSecret>"
#    redirect-uri: "http://localhost:3000/authenticate"

  application:
    name: spring-ai-demo
  ai:
    openai:
      api-key: AIzaSyAIJKmUv5NEbHsgVP01052OfHG1jMj_Zy8
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-1.5-flash

# JWT Configuration
jwt:
  signerKey: "wYUihtKXpSs/+rDJXC2wdSpL0O03rp7UK7KGk4+GoQkSPaRJ8z3//8hvl+NBOIams3cweOfBvBoyFXceds/VxA=="
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

# Gemini AI Configuration
gemini:
  api-key: AIzaSyCz_WwsloQnnBcx5AhTW8pv_rH5758X-js
  model: gemini-1.5-flash

# Cloudinary Configuration
cloudinary:
  cloud-name: mito
  api-key: 885716972975153
  api-secret: YjMVc_vvJAewdntYU4j0kFOaEV4


