server:
  port: 8080
  servlet:
    context-path: /calmistry

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://metro.proxy.rlwy.net:24473/calmistry}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:vNuRxEsasQqlbOZUsraXWnRGoQIqXkVN}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: spring-ai-demo
  ai:
    openai:
      # GitHub will block if literal key is here. Use Environment Variable locally.
      api-key: ${SPRING_AI_KEY:your_spring_ai_proxy_key}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-1.5-flash

# JWT Configuration
jwt:
  signerKey: ${JWT_SIGNER_KEY:your_jwt_signer_key}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

# OpenAI Configuration
openai:
  api-key: ${OPENAI_API_KEY:your_openai_key}
  model: gpt-4o

# Gemini AI Configuration
gemini:
  api-key: ${GEMINI_API_KEY:your_gemini_key}
  model: gemini-1.5-flash

# Cloudinary Configuration
cloudinary:
  cloud-name: ${CLOUDINARY_NAME:dculsqafi}
  api-key: ${CLOUDINARY_API_KEY:your_cloudinary_key}
  api-secret: ${CLOUDINARY_API_SECRET:your_cloudinary_secret}
