server:
  port: 8080
  servlet:
    context-path: /calmistry

spring:
  datasource:
    url: ${DB_URL:}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#outbound:
#  identity:
#    client-id: "<clientId>"
#    client-secret: "<clientSecret>"
#    redirect-uri: "http://localhost:3000/authenticate"

  application:
    name: spring-ai-demo
  ai:
    openai:
      api-key: sk-proj-dummy-key-force-startup-12345
      base-url: ${SPRING_AI_BASE_URL:}
      chat:
        options:
          model: gpt-5.2

# JWT Configuration
jwt:
  signerKey: ${JWT_SIGNER_KEY:}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

# OpenAI Configuration
openai:
  api-key: ${OPENAI_API_KEY:sk-dummy-key-to-bypass-startup-check}
  model: gpt-5.2



# Cloudinary Configuration
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}
